language: julia
os:
  - linux
  - osx
julia:
  - 0.4
# - nightly  # need to fix this

notifications:
  email: false

before_install:
  - if [ `uname` = "Linux" ]; then
      sudo apt-get update -qq;
      sudo apt-get install build-essential gfortran perl g++ gcc cmake m4 git;
      sudo apt-get install -y liblapack-dev liblapack-doc liblapack3gf;
      sudo apt-get install -y libblas-dev libblas-doc libblas3gf;
      echo `pwd`;
    fi
install:
  - ls ./deps
  - ls -lh ./deps/travis-install-mpi.sh
  - if [ `uname` = "Linux" ]; then
      sudo ./deps/travis-install-mpi.sh mpich3;
    elif [ `uname` = "Darwin" ]; then
      sudo ./deps/travis-install-mpi.sh openmpi;
    fi
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("PETSc")'
  - echo $HOME
  - echo `pwd`
  - julia --check-bounds=yes -e 'Pkg.test("PETSc"; coverage=true)'
#  - julia --check-bounds=yes ./test/test_singlereal.jl

after_success:
  - echo $TRAVIS_JULIA_VERSION
  - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("PETSc")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
  - julia -e 'Pkg.clone("https://github.com/MichaelHatherly/Documenter.jl")'
  - julia -e 'cd(Pkg.dir("PETSc")); include(joinpath("docs", "make.jl"))'
